/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BIL402_HW3;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test public void testHasBiggerValue(){
        ArrayList<Integer> arr = new ArrayList<>(Arrays.asList(2,18,12,10));
        assertTrue(App.BiggerThanSum(arr, 3, 5, 7));
    }

    @Test public void testHasNotBiggerValue(){
        ArrayList<Integer> arr = new ArrayList<>(Arrays.asList(1,2,3,4));
        assertFalse(App.BiggerThanSum(arr, 3, 5, 7));
    }

    @Test public void testEmptyArray(){
        ArrayList<Integer> arr = new ArrayList<>();
        assertFalse(App.BiggerThanSum(arr, 1, 2, 3));
    }

    @Test public void testNull(){
        assertFalse(App.BiggerThanSum(null, 1, 2, 3));
    }

    @Test public void testValueZero(){
        ArrayList<Integer> arr = new ArrayList<>(Arrays.asList(1,2,3,4));
        assertFalse(App.BiggerThanSum(arr, 0, 0, 0));
    }

}
