/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BIL402_HW3;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static boolean search(ArrayList<Integer> arr, int e){
        System.out.println("Inside search");
        if (arr == null ) {
          return false;
        }
  
        for (int elt:arr) {
          if (elt==e) {
            return true;
          }
        }
        return false;
  
      }
}
